name: Go CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set up cross-compilation
        run: sudo apt install -y libpcap-dev gcc-aarch64-linux-gnu libc6-dev-arm64-cross
      - name: Install dependencies
        run: make depend
      - name: Build with Go
        run: make release-build
      - name: Publish to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            out/ci/liwasc-backend/*
            out/ci/liwasc-frontend/*
